<?php
return [
'a11y'=>['skip'=>'Перейти к содержимому','primary_nav'=>'Основная навигация','menu'=>'Меню'],
'nav'=>['home'=>'Главная','about'=>'О VALDR','story'=>'История','technology'=>'Технология','download'=>'Скачать','verify'=>'Проверка','mining'=>'Майнинг','node'=>'Запустить ноду','wallet'=>'Кошелёк','explorer'=>'Explorer','security'=>'Безопасность','roadmap'=>'Roadmap','community'=>'Сообщество','faq'=>'FAQ','docs'=>'Документация','releases'=>'Релизы','more'=>'Ещё'],
'status'=>['testnet'=>'VALDR TESTNET','mainnet_not_launched'=>'Mainnet не запущен'],
'buttons'=>['download'=>'Скачать VALDR','explore'=>'Смотреть сеть','story'=>'Читать историю','source'=>'Исходный код','verify'=>'Проверить загрузку','docs'=>'Документация'],
'footer'=>['line'=>'NOT A TOKEN. A CHAIN.','testnet_notice'=>'VALDR сейчас находится на этапе разработки Testnet. Testnet VDR не имеет обещанной денежной стоимости.','project'=>'Проект','resources'=>'Ресурсы','source'=>'Исходный код','no_investment'=>'Нет ICO, presale, листинга или инвестиционных обещаний.'],
'pages'=>[
'home'=>['title'=>'VALDR','meta_title'=>'VALDR (VDR) — независимый Proof-of-Work блокчейн','meta_description'=>'VALDR — независимая Proof-of-Work криптовалюта на собственном блокчейне. Идёт разработка Testnet.','kicker'=>'Независимый блокчейн','lead'=>'Свой блокчейн. Proof of Work. Открытая сеть.'],
'about'=>['title'=>'Что такое VALDR?','meta_title'=>'Что такое VALDR (VDR)?','meta_description'=>'VALDR — независимая Proof-of-Work криптовалюта с собственным Go-блокчейном, UTXO, P2P-сетью и native-монетой VDR.','kicker'=>'О VALDR','lead'=>'VALDR — независимая Proof-of-Work криптовалюта, работающая на собственном блокчейне.','sections'=>[
 ['heading'=>'Цепочка, а не токен','paragraphs'=>['VDR — native-монета блокчейна VALDR. Консенсус, транзакции, майнинг и владение не зависят от Ethereum, BNB Chain, Solana или другой сети.'],'bullets'=>['Собственная реализация блокчейна на Go','Proof of Work','UTXO-модель транзакций','Независимые P2P-ноды','Собственные VDR-адреса и монета']],
 ['heading'=>'Что существует сейчас','paragraphs'=>['В линейке v0.2 реализованы и подтверждены CI: усиленная нода, Storage v2, P2P v2, chainwork/reorganization, комиссии, mempool policy, полная синхронизация, шифрование кошелька, Explorer и Testnet runtime/Linux/Docker инфраструктура. VALDR Desktop находится в активной разработке. Public Testnet и Mainnet не запущены.']],
 ['heading'=>'Философия проекта','paragraphs'=>['Не власть над другими. Власть над своим. Свои ключи. Своя монета. Своя нода. Свой выбор. Северная тема — современная визуальная и философская основа, а не выдуманная древняя история.']]
]],
'story'=>['title'=>'История VALDR','meta_title'=>'История создания VALDR','meta_description'=>'Как VALDR прошёл путь от простой идеи и эксперимента с Bitcoin Core к самостоятельному Proof-of-Work блокчейну на Go.','kicker'=>'От идеи к цепочке','lead'=>'VALDR начался с простой идеи: а что если создать собственную монету — не ещё один токен в чужой сети?','sections'=>[
 ['heading'=>'Идея','paragraphs'=>['Первым ориентиром стал Bitcoin: сеть, где владение и действительность транзакций определяются самим протоколом. Ранний эксперимент с Bitcoin Core помог прояснить направление, но целью стала самостоятельная реализация VALDR.']],
 ['heading'=>'Собственный блокчейн на Go','paragraphs'=>['Активный проект перешёл на Go и сохранил ключевые принципы Bitcoin-подобной денежной сети: UTXO, Proof of Work, независимые ноды, подписанные транзакции и собственную монету. Эксперимент с Bitcoin Core сохранён в архиве и не является активной архитектурой.']],
 ['heading'=>'Сначала сеть, потом рынок','paragraphs'=>['VALDR развивается последовательно: спецификация → реализация → сборка → тестирование → проверка → следующий этап. AI-инструменты используются как технический партнёр разработки. VALDR не начинался с ICO, presale или заранее проданного токена. Сначала строится рабочая независимая сеть.']],
 ['heading'=>'Timeline','cards'=>[['title'=>'Идея','text'=>'Создать собственную монету и независимый блокчейн.'],['title'=>'Эксперимент Bitcoin Core','text'=>'Ранний технический эксперимент, позже перенесённый в архив.'],['title'=>'Свой Go-блокчейн','text'=>'Самостоятельная реализация VALDR становится активной архитектурой.'],['title'=>'Devnet v0.1','text'=>'Рабочий трёхузловой Devnet: wallet, miner, P2P, RPC/CLI и сохранение состояния.'],['title'=>'Hardened v0.2','text'=>'Этапы 0–11 реализованы и подтверждены CI.'],['title'=>'VALDR Desktop','text'=>'Находится в разработке в ветке v0.2.'],['title'=>'Public Testnet','text'=>'Запланирован, но не запущен.'],['title'=>'Future Mainnet','text'=>'Не запущен; требуется отдельное утверждённое ТЗ.']]]
]],
'technology'=>['title'=>'Технология','meta_title'=>'Технология VALDR','meta_description'=>'Подтверждённая архитектура VALDR v0.2: Go, SHA-256 Proof of Work, UTXO, P2P v2, chainwork, reorg, шифрованный кошелёк и Testnet.','kicker'=>'Протокол','lead'=>'Здесь указаны только характеристики, подтверждённые актуальным Master TZ и репозиторием VALDR.','sections'=>[
 ['heading'=>'Ядро протокола','cards'=>[['title'=>'Независимая цепочка','text'=>'Одна каноническая реализация блокчейна на Go.'],['title'=>'Proof of Work','text'=>'SHA-256 хэширование блоков и правила сложности из network profile.'],['title'=>'UTXO','text'=>'Входы тратят подтверждённые unspent outputs; стоимость сохраняется, комиссия не хранится отдельным полем.'],['title'=>'Chainwork + reorg','text'=>'Активная ветка выбирается по накопленной chainwork с атомарным rollback/reconnect.'],['title'=>'P2P v2','text'=>'Разделение сетей, version negotiation, checksums, лимиты и защита от abuse.'],['title'=>'Full sync','text'=>'Headers-first синхронизация с проверкой до загрузки тел блоков.']]],
 ['heading'=>'Профиль Testnet','bullets'=>['Chain ID: valdr-testnet-1','Целевой интервал блока: 60 секунд','P2P: v2','P2P порт: 17333','RPC: 17332, localhost по умолчанию','Префикс адреса: VDR1','Максимальный канонический размер блока: 1 000 000 байт','Текущая Testnet subsidy: 50 Testnet VDR только для тестирования протокола']],
 ['heading'=>'Кошелёк и сервисы','bullets'=>['Encrypted wallet v2; новые wallet-файлы не содержат plaintext private key','scrypt-derived key + AES-256-GCM','Read-only Explorer с учётом reorg','RPC localhost по умолчанию','Storage v2 на BadgerDB','Docker и Linux service deployment для инфраструктуры']]
]],
'mining'=>['title'=>'Майнинг','meta_title'=>'Майнинг VALDR Testnet','meta_description'=>'Как работает Proof-of-Work майнинг VALDR, роли node и miner, ограничения текущего Testnet.','kicker'=>'Proof of Work','lead'=>'VALDR использует Proof of Work. Майнер предлагает блоки, а каждая нода самостоятельно проверяет результат.','notice'=>['type'=>'warning','title'=>'Только Testnet','text'=>'Testnet VDR не имеет обещанной денежной стоимости. Текущие параметры награды — параметры тестирования протокола, а не обещание Mainnet-экономики.'],'sections'=>[
 ['heading'=>'Что делает майнинг','paragraphs'=>['Майнер собирает кандидатный блок из действительных транзакций, выполняет Proof-of-Work и передаёт блок VALDR-нode. Нода проверяет блок по consensus rules до включения в активную цепь.']],
 ['heading'=>'Домашний майнинг','paragraphs'=>['Официальное ПО включает miner для Devnet/Testnet. Майнинг в Desktop должен оставаться явным opt-in действием: он никогда не должен запускаться скрытно в браузере или на компьютере пользователя.']],
 ['heading'=>'Node, miner и железо','cards'=>[['title'=>'Node','text'=>'Проверяет правила цепи, хранит состояние, синхронизируется и обслуживает локальный RPC.'],['title'=>'Miner','text'=>'Получает/строит работу, хэширует заголовки и отправляет найденные блоки.'],['title'=>'CPU / ASIC','text'=>'Сейчас проект проверяет протокол. Прибыльность и будущая экономика оборудования не обещаются.']]]
]],
'node'=>['title'=>'Запустить ноду','meta_title'=>'Запустить ноду VALDR','meta_description'=>'Что делает нода VALDR, outbound-only режим Desktop, public full node и текущий статус Testnet-инфраструктуры.','kicker'=>'Проверяй сеть сам','lead'=>'Нода самостоятельно проверяет блоки и транзакции, а не доверяет копии цепочки от третьей стороны.','notice'=>['type'=>'info','title'=>'Текущий статус','text'=>'Node/Testnet runtime реализован и подтверждён CI. VALDR Desktop пока разрабатывается; публичная Testnet-инфраструктура ещё не запущена.'],'sections'=>[
 ['heading'=>'Что такое node?','paragraphs'=>['VALDR-нода хранит проверенное состояние блокчейна, проверяет Proof of Work и транзакции, синхронизируется с peers и relay подтверждённые данные. Если компьютер выключен, нода просто перестаёт участвовать; после запуска она продолжает синхронизацию из сохранённого состояния.']],
 ['heading'=>'Обычный пользователь','paragraphs'=>['VALDR Desktop проектируется так, чтобы автоматически запускать локальную outbound-only ноду. Для этого режима не нужны port forwarding и открытие входящего P2P-порта на домашнем роутере.']],
 ['heading'=>'Advanced и сервер','cards'=>[['title'=>'Advanced Desktop','text'=>'Для публично доступной full node предусмотрен отдельный осознанно включаемый режим.'],['title'=>'Linux server','text'=>'Stage 11 включает Linux/Docker deployment и localhost-only RPC по умолчанию.'],['title'=>'Public node','text'=>'Публичная нода требует явного открытия P2P, мониторинга и hardening. По умолчанию это не включается.']]]
]],
'wallet'=>['title'=>'Кошелёк','meta_title'=>'Безопасность кошелька VALDR','meta_description'=>'Основы VALDR wallet: VDR-адрес, private key, encrypted wallet, backup, send и receive.','kicker'=>'Ключи остаются у тебя','lead'=>'Кошелёк управляет private key, которым подписывается расходование средств. Официальному сайту этот ключ никогда не нужен.','notice'=>['type'=>'danger','title'=>'Никогда не вводи private key на сайте','text'=>'Этот сайт не является custodial wallet и не собирает private keys, passphrases или wallet passwords.'],'sections'=>[
 ['heading'=>'Базовые понятия','cards'=>[['title'=>'VDR address','text'=>'Публичный адрес для получения VDR. Текущий префикс адресов — VDR1.'],['title'=>'Private key','text'=>'Секрет, дающий право подписывать расходование. Его нельзя передавать другим людям или сайтам.'],['title'=>'Encrypted wallet','text'=>'Wallet v2 локально шифрует ключевой материал с использованием ключа, полученного из passphrase, и authenticated encryption.']]],
 ['heading'=>'Отправка и получение','paragraphs'=>['При отправке транзакция создаётся и подписывается локально, затем передаётся через ноду. Для получения достаточно сообщить публичный VDR-адрес. Подтверждённые транзакции следует считать необратимыми.']],
 ['heading'=>'Backup','paragraphs'=>['Резервная копия защищает от потери устройства или диска. Храни backup отдельно от компьютера с нодой и никогда не загружай private-key material на этот сайт.']]
]],
'security'=>['title'=>'Безопасность','meta_title'=>'Безопасность VALDR','meta_description'=>'Принципы безопасности сайта и кошелька VALDR, проверка загрузок, localhost RPC и non-custodial архитектура.','kicker'=>'Verify, do not trust','lead'=>'Безопасность для VALDR — обязательная граница архитектуры, а не рекламная функция.','sections'=>[
 ['heading'=>'Границы сайта','bullets'=>['Нет форм для private key или wallet password','Нет browser cryptomining','Нет analytics или скрытых trackers по умолчанию','Нет удалённого произвольного JavaScript','Нет автоматической загрузки executables','Content Security Policy и строгие browser headers']],
 ['heading'=>'Границы node/wallet','bullets'=>['RPC по умолчанию слушает localhost','Private keys и passphrases не передаются по P2P или node RPC','Encrypted wallet v2 не хранит plaintext private key в новых wallet-файлах','Desktop core assets должны быть локальными','Public-node режим включается явно, а не по умолчанию']],
 ['heading'=>'Загрузки','paragraphs'=>['Installers появятся только после существования реальных release artifacts, hashes и signing metadata. До этого сайт сознательно не показывает ссылки на executable downloads.']]
]],
'verify'=>['title'=>'Проверка загрузок','meta_title'=>'Проверить загрузки VALDR','meta_description'=>'Как проверять будущие VALDR releases по SHA-256 и подписанному release manifest. Фиктивные hashes не публикуются.','kicker'=>'Целостность релиза','lead'=>'Проверка помогает обнаружить повреждённый или подменённый файл до запуска.','notice'=>['type'=>'info','title'=>'Проверенного installer release пока нет','text'=>'Сейчас нет официального manifest для VALDR Desktop installers, поэтому здесь нет placeholder hashes или signatures.'],'sections'=>[
 ['heading'=>'Модель проверки','bullets'=>['Скачать release file только из официального release location','Скачать подписанный release manifest','Проверить подпись manifest по официальному release key','Посчитать SHA-256 скачанного файла','Сравнить каждый символ hash с подписанным manifest']],
 ['heading'=>'Windows','code'=>'certUtil -hashfile <VALDR-release-file.exe> SHA256'],['heading'=>'macOS','code'=>'shasum -a 256 <VALDR-release-file.dmg>'],['heading'=>'Linux','code'=>'sha256sum <VALDR-release-file.tar.gz>'],
 ['heading'=>'Не пропускай проверку подписи','paragraphs'=>['Совпавший hash связывает файл с manifest. Доверенная подпись связывает сам manifest с официальным release process. Точные команды и fingerprints будут опубликованы только вместе с реальным signing pipeline.']]
]],
'faq'=>['title'=>'FAQ','meta_title'=>'VALDR FAQ','meta_description'=>'Ответы на вопросы о VALDR, Testnet, майнинге, кошельке, нодах и статусе Mainnet.','kicker'=>'Вопросы','lead'=>'Короткие ответы по фактическому состоянию проекта v0.2.','sections'=>[
 ['heading'=>'VALDR — токен Ethereum, BNB Chain или Solana?','paragraphs'=>['Нет. VALDR — собственный блокчейн, а VDR — его native-монета.']],
 ['heading'=>'Mainnet уже работает?','paragraphs'=>['Нет. Mainnet не запущен, и его финальная monetary specification пока не утверждена.']],
 ['heading'=>'Можно купить или торговать VDR?','paragraphs'=>['На текущем этапе у официального проекта нет ICO, presale или exchange listing. Testnet VDR не имеет обещанной денежной стоимости.']],
 ['heading'=>'Можно запустить ноду дома?','paragraphs'=>['Да, архитектура это предусматривает. Desktop рассчитан на outbound-only локальную ноду, а публичная inbound-нода — advanced режим. Сам Desktop ещё разрабатывается.']],
 ['heading'=>'Сайт хранит мои ключи?','paragraphs'=>['Нет. Сайт non-custodial и не должен запрашивать или хранить private keys, passphrases или wallet passwords.']],
 ['heading'=>'Где скачать программу?','paragraphs'=>['Проверенных публичных Desktop installers пока нет. Кнопки загрузки останутся отключёнными, пока не появятся реальные подписанные release artifacts.']]
]],
'docs'=>['title'=>'Документация','meta_title'=>'Документация VALDR','meta_description'=>'Официальные точки входа в документацию VALDR для пользователей, операторов нод, разработчиков и проверки релизов.','kicker'=>'Documentation','lead'=>'Актуальный технический source of truth — ветка v0.2 и последняя Master Specification.','sections'=>[
 ['heading'=>'Для пользователя','cards'=>[['title'=>'Wallet','text'=>'Ключи, адреса, backup, send и receive.'],['title'=>'Run a Node','text'=>'Роль ноды, домашний и серверный режим.'],['title'=>'Mining','text'=>'Proof of Work и ограничения текущего Testnet.'],['title'=>'Verify Downloads','text'=>'Проверка hash/signature релизов.']]],
 ['heading'=>'Для разработчика и оператора','paragraphs'=>['Каноническая реализация находится в Sheff1981/valdr-core, ветка valdr-v0.2. На момент подготовки сайта актуальная Master Specification — v0.2.4. Контент сайта должен обновляться при каждом подтверждённом изменении продуктового статуса.']]
]],
'explorer'=>['title'=>'Explorer','meta_title'=>'VALDR Testnet Explorer','meta_description'=>'Статус VALDR Explorer. Сайт не является block explorer; отдельный read-only Testnet endpoint будет добавлен после публикации.','kicker'=>'Видимость сети','lead'=>'VALDR Explorer — отдельный read-only сервис. Этот сайт не дублирует его.','notice'=>['type'=>'info','title'=>'Testnet Explorer — скоро','text'=>'ПО Explorer реализовано и подтверждено CI, но официальный публичный Explorer endpoint пока не опубликован.'],'sections'=>[
 ['heading'=>'Что показывает Explorer','bullets'=>['Последние блоки и детали блока','Поиск транзакций','Баланс/history/UTXO адреса','Mempool и network status','Difficulty и недавние интервалы блоков','Reorg-aware indexing']],
 ['heading'=>'Только чтение','paragraphs'=>['Explorer не содержит private keys, signing controls, mining controls или privileged node operations. Источником истины остаётся нода.']]
]],
'community'=>['title'=>'Сообщество','meta_title'=>'Сообщество VALDR','meta_description'=>'Официальные каналы VALDR появятся здесь только после их создания и проверки. Выдуманные social links не публикуются.','kicker'=>'Community','lead'=>'Официальные каналы добавляются только после фактического создания и проверки.','sections'=>[
 ['heading'=>'Текущие каналы','cards'=>[['title'=>'GitHub','text'=>'Исходный код проекта ведётся в GitHub-аккаунте Sheff1981.'],['title'=>'Telegram','text'=>'Скоро.'],['title'=>'VK','text'=>'Скоро.'],['title'=>'X','text'=>'Скоро.'],['title'=>'Reddit','text'=>'Скоро.'],['title'=>'Discord','text'=>'Скоро.']]],
 ['heading'=>'Остерегайся подделок','paragraphs'=>['Пока канал не указан на этой странице как официальный, не считай аккаунт с названием VALDR представителем проекта.']]
]],
'releases'=>['title'=>'Релизы','meta_title'=>'Релизы VALDR','meta_description'=>'Официальные релизы VALDR и статус проверки. Публичных installer artifacts пока нет.','kicker'=>'Release channel','lead'=>'Здесь могут появляться только реальные проверенные artifacts.','notice'=>['type'=>'info','title'=>'Публичного installer release пока нет','text'=>'В GitHub-репозитории сейчас нет опубликованных Releases. Cross-platform installers и release-signing pipeline — следующий отдельный этап v0.2.'],'sections'=>[
 ['heading'=>'Правила релиза','bullets'=>['Нет релиза без реального artifact','Каждый artifact получает SHA-256','Release manifest должен быть подписан','Release notes указывают commit и network','Перед пометкой ready должны пройти CI/runtime проверки']],
 ['heading'=>'Development source','paragraphs'=>['Текущая разработка идёт в valdr-v0.2. Development commit не равен опубликованному installer release.']]
]],
'download'=>['title'=>'Скачать VALDR','meta_title'=>'Скачать VALDR Testnet','meta_description'=>'Страница загрузки VALDR Testnet. Проверенные installers появятся только после готовности cross-platform release/signing pipeline.','kicker'=>'Официальное ПО','lead'=>'Скачивай только проверенное ПО VALDR. Публичного Desktop installer release пока нет.'],
'roadmap'=>['title'=>'Roadmap','meta_title'=>'Roadmap VALDR','meta_description'=>'Фактический roadmap VALDR: реализовано, в разработке, запланировано и не запущено.','kicker'=>'Проверенный прогресс','lead'=>'Этап считается завершённым только после реализации и проверочного evidence, а не просто после появления кода.']
]
];
